#include <stdio.h>
#include <stdlib.h>
#define L(s)  printf(#s);
//#define ) "\"");

int main(void) {
L( NNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN )
L(                          mmmmmmNNNNNNNNN                                     )
L(                        NmmmNNNNNNNNNNNNNNN                                   )
L(                       mmmmmmmdddddddmNNNNNN                                  )
L(                       mddhyoooooosssyhdmmNNNN                                )
L(                      Nds+++/+++++oossyyhdmNNNN                               )
L(                      dy+:/+||/+++ooosyyydmmNNN                               )
L(                      hy||o+o+++++osyyyhhhdmNNNN                              )
L(                      ds+syhdhyoosyhdhhhddhdNNNN                              )
L(                      d+oyhhddhooyhdhdddhhhhNNNN                              )
L(                     Ny+/osyyys+oyyyyyyyyyyhNmdd                              )
L(                      y||/++o+++oyyssoossyyhmdyyN                             )
L(                      y+||++ooysshysoooossyhhyyh                              )
L(                      m/+oooo+ossyyssssssyhhysyN                              )
L(                       h+oosyyysssyhhssssyhhmdm                               )
L(                        hooo+ossssssoosssyhd                                  )
L(                         doo++++ooooossyyyym                                  )
L(                         N+ooo+oooossyyyysym                                  )
L(                          ooossyyyyyyyysssyddd                                )
L(                         do+++osssssssssssyds/y                               )
L(                        m/s+++oooosssssssso/::/y                              )
L(                       m:.so++oossoooso+/:--::::+oydm                         )
L(                    Ny/.`-:oso+ooooo+/-----:::::----:/oyhmN                   )
L(                Nmdo-.../+:-:sooooo-:/+:--::-::-----------:+shm               )
L(            ms+:-...-...:::::/oooo:----:-----------------------:+ym           )
L(          h/.............-....-o+/......:-----------..---.--------:sN         )
L(        m/...`.......`.........s+......---....--..........--------::oN        )
L(       y-...........``.......`./-..`..--......-...........-:-----::::oN       )
L(      m..............`...............-...................-:------::::/s       )
L(      y.............................-...................-:-.---::::::::s      )
L(      +........................```.....................:::----::::-:::::m     )
L(     d...........................................------:/:---:::--:::--+N     )
L(     /..--...................................------::::||::::::--::--:/sN     )
L(    N-..-:--:--.............................---..-::::/oo+::::-----::::/oN    )
L(    N-...:||:-.---..........................------:::||os/::------:----:+N    )
L(    d...--:||:/-............................------:::||so/::::::------::/d    )
L(   N/..----:||:...........--...............-----:::::||so/:/::----------:+N   )
L(   y...----:/+/-...----.----....-........-.-----:::::::/s/:::------------:y   )
L(  m-...--::||/o/------..--.................----:::::::::++/:::::---------:/m  )
L(  o...---:::||o/.----..--..................-----::::----:+o+||::---------::oN )
L( d-...--:::/++o:.---......................-----:::-------/sh+/::::--------::d )
L( N....---::||+s-.---.........`...........-----::--------:/ohhs+/:---------::s )
L( y..------::/+o..--.......---::---....--.-----:--------:||yddhso+||::------:N )
L( y:||++++++++os---......./++ooo++||/---------:-------:||++yyssooooosssoo+/::d )
L( y+++++ooooooss:--....--:/ooooo+/+oo+/:------------:/++ossoooooooossssssyysod )
L( Noo+++++++++++++||||/+/++++ooo+osoooooo+||||||/++oooooooooooooooosssssyyyyyN )
L( mysoooo+++++++++++||+++ssoo++/+oooooooooooooooossoosooooooossssssssyyyyyyyN  )
L(  dyyyssoooooooooooo||+++oyyo+oooooosooooooos/oysssssssssssssssyyyyyyhhyhhm   )
L(   mdhhyyyyyyyyyyyssoo++++++++++osssssssssshsyysosssssyyyyyyyyyyhhhhddmN      )
L(     Nmdhhhhhhhhhhhho+osyyyysssssyyyyyyyyyshs+os+yyyyyyyyyhhhhddmNN           )
L(        NNNNNmmdhhysoooooosssssyyyyyyyyssssyso+osssssyyyyyhmN                 )
L(               mo+||/:/ossysssssssso+||:||||/:::::::::||||s                   )
L(               N/::--:::::+oo+++++||:::::--------:::::::::/sd                 )
L(                m:.----:--:::::||/:::::----------:--::::::::+N                )
L(               m/.-:::-..------:::::----------------------:/m                 )
L(               d-.........------:::::---------------:::::++m                  )
L(                d:::-----:/::-::::::---::::||+oyyyyhhhddhs/s                  )
L(               h:.+dd+ysoo++||||||||+++-/syhdddmmmNNNds+:::/y                 )
L(             m+.``.:s/dmmmyys+yyhdshddd+-dmmmNNNmdhyo:----:||d                )
L(            m:``````../oydyddmmmmmdyNNmm:omdhys+:---..-----:/+m               )
L(           N/.```````...--/hdmmmmmmydhys+:/--.........------:/d               )
L(           d...``.........-:++o++||:::---..............----:::d               )
L(           d-.................-..-.....................---::--o               )
L(           Ny/.........................................--:::--/N              )
L(             d-....................................-----::::--/N              )
L(             m........................................----::::o               )
L(             d..............----.......................----:::s               )
L(             y`.....-------------------.-..-..........-----:::/d              )
L(             o......--......--:--::----------..........------:/+N             )
L(             +........--::::--:::----------------......------::+N             )
L(            N:.......-----:::::/+/:::::-------..........-----:/+N             )
L(            N:............--::||+os+::------.............---::/h              )
L(            m.....------..----::/+os::::::::-...---......---::/m              )
L(            m.....-------------:::/+/:||/:-----..........---:::m              )
L(            d`...------:::::-----:/+oo-----::---.........---::/N              )
L(            h`...-----------:::--::/+o:||::-----..........--::/N              )
L(            h`...---------------:::/+s/:------------......--:::N              )
L(            h`...----------------::/+ss:::---------.......---::m              )
L(            d....--------------:::::+sd/:------------......--::d              )
L(            m..-------------------:/+s y::---------.......--:::h              )
L(            m---------------------:/oh N+:-----------.....--:::y              )
L(            N-..-----------------::/+m  d::-----------.------::o              )
L(            N:.-------------------:/oN   +:::----------------::+              )
L(            N:.-------------------:/o    y::::---------------::/N             )
L(            N:.-------------------:/+N   m::-----------------::/m             )
L(             /.--------------------:+N   N:-::---------------:::d             )
L(             o.-------------------:/y    N/:::::-------------::-o             )
L(             Ny+||:----::::||/+++osd      mo/:----------------:-:N            )
L(                 Nmyyyssyyyyyyyssssm        ds+/:-------------/od             )
L(                   Nhhhhhyyyyysssyym         dhhys+||::::::/+sm               )
L(                    Nhddhhhhyyssyyhm         NhhhhhhhhhyyhhhhhN               )
L(                     yhdddhhyyyyyhhd          Nhhhhhhhhhhhhhhhd               )
L(                     syyhhhyyyyyyyyhN          Nhhddddddhhhhhhhm              )
L(                    Nsssyyyyyyyyyyyym           mhhhdddddhhyyyhdN             )
L(                    Nsssyyyyysssssyyh           Nhhhhhhhhyyyyyhhm             )
L(                    Nsssssyyssssssyyh           Nhyyyyyyyysssyhhd             )
L(                     ysssssssssssssyh            hyyyyyyyysssyyhd             )
L(                     hyssssyyyssssyyh            dyyyyyysssssyyhh             )
L(                     dsyysyysysssyyhm            myyyyyyyssssyyhh             )
L(                     msyyyyyyssyyyhm             Nyyyyyyyyssyyyhh             )
L(                     msyyyyyyssyyhd               myyyyyyyyyyyyhd             )
L(                     NsyyyyyyyyyyhN               Nyyyyyyyysyyyhd             )
L(                      yyyyyyyyyyyd                 myyyyyyysyyyhd             )
L(                      hsyyyyyyyyhd                  hyyyyyyyyyyhd             )
L(                      mssyyyyyyyhd                  myyyyyyyyyhhm             )
L(                      Nossssssyyym                   hyyyyyyyyhhN             )
L(                      Nooooossssym                   hyyyyysyyhd              )
L(                      m+oooooossym                   myssssssyyd              )
L(                      d++ooooossym                   Nsoosoossym              )
L(                      h+++++oossym                    soooooosy               )
L(                      y+++/++osssm                   Nooooooosd               )
L(                      s||||+++oysh                   d+++oooosm               )
L(                     m+||/+++ossydm                  y+++++oosd               )
L(                  Nmy+||/+++ossyddmm                 o+++++oosyN              )
L(               Nmdhhyyo++++ooyhdddmm                N++++++oosym              )
L(             Nmdddhhhdhs++osydddmmmN                do+++++oossmN             )
L(         NmdyyyyyhhhhhhhyyhdmmmmmNN                 yy+++oooossmmN            )
L(      NmdhyyyssyyhyhhdhdddmmNNN                     yyoyhhyhhhhhmdN           )
L(     dyyhhyyyyyhdhhhdddmNN                         Nyhhhdhddhdddmmd           )
L(     yyhhhhhhhhhhdddmN                             myyyhdddddddddmdN          )
L(     NddhhhhddddmmN                                Nhyhhhhhdddddddmm          )
L(        NNNNN                                      NhhhhhhhhddddhdmN          )
L(                                                    hyhhhhhhddhhmmmN          )
L(                                                    dhyyyhhhdddmmmN           )
L(                                                    mhhhhhhhhdmmmN            )
L(                                                     NhhhdddddmmN             )
L( NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmNNNNNNNNNNNNNNNN )

	return EXIT_SUCCESS;
}
